### ISSUE TITLE
txid error, not receive coin CNT

### ISSUE THREAD

**Issue by ailaah** [centurioncoin/centurion#1]
Dear....
Please ceck this issue 2017-12-07 10:56:45
774.11385081 CNT
8d73c8fddaaddde39f5d6ee8af1a728d92c04890245ad53e2961766b4d1c1693
Cbq4gbpFWmavqYAyEUkcX1u75H1X6RVUei

Thank you

**Comment by doghie5** [comment]
is your issue already solve?

**Comment by doghie5** [comment]
i've got the same issue and i dnt know where to ask support

**Comment by ailaah** [comment]
No, not now just wait

**Comment by centurioncoin** [comment]
You can't send old chain coin to the new one. After block 738.000 there's a fork. Some exchangers did not update to new coin yet, so you need to understand how to transfer the coins correctly. We suggest the windows physical wallet so all coins will be updated to the new chain until block 738.000

**Comment by ailaah** [comment]
I sent coin from date  2017-12-07 10:56:45
774.11385081 CNT, if this coin cant to transfer please give it back to my balance ! Thanks
