### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by totocamen88** [centurioncoin/centurion#3]
Hi!

I have a problem with my wallet.
It don't update last block but it's stopped at block 850209.
There is 1 connection but don't update.

**Comment by totocamen88** [comment]
How can I add nodes?

**Comment by myfoxx** [comment]
Close you wallet.

You can add node by create a file centurion.conf under your %appdata%\centurion folder, and insert  this four lines:
addnode=46.101.2.6
addnode=88.99.194.16
addnode=188.166.16.47
addnode=159.203.36.40

Save and close file. on the same folder delete the peers.dat file then restar you wallet.

**Comment by totocamen88** [comment]
don't work....

Now I haven't any connection

**Comment by totocamen88** [comment]
This is my debug log
[debug - Copia.txt](https://github.com/centurioncoin/centurion/files/1613229/debug.-.Copia.txt)

**Comment by centurioncoin** [comment]
This is correct:

Close you wallet.

You can add node by create a file centurion.conf under your %appdata%\centurion folder, and insert this four lines:
addnode=46.101.2.6
addnode=88.99.194.16
addnode=188.166.16.47
addnode=159.203.36.40

Save and close file. on the same folder delete the peers.dat file then restar you wallet.
